echo "--- Executing initialization force file for ../mp3/ECE411/mp3/tests/traptest.asm ---"

echo "Resetting processor for 5 ns."
force /reset_l 0 @0
force /reset_l 1 @5
echo "Initializing the processor."
force /start_h 0 @0
force /start_h 1 @10

-- Test case: lowering start_h should not impact the function of the processor
force /start_h 0 @ 100

echo "Done initializing processor, loading ../mp3/ECE411/mp3/tests/traptest.asm program code."
run 5
change /mp3_cpu/TM/VHDL_MEMORY/mem(0) X"28"
change /mp3_cpu/TM/VHDL_MEMORY/mem(1) X"E0"
change /mp3_cpu/TM/VHDL_MEMORY/mem(2) X"21"
change /mp3_cpu/TM/VHDL_MEMORY/mem(3) X"12"
change /mp3_cpu/TM/VHDL_MEMORY/mem(4) X"29"
change /mp3_cpu/TM/VHDL_MEMORY/mem(5) X"F0"
change /mp3_cpu/TM/VHDL_MEMORY/mem(6) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(7) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(8) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(9) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(10) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(11) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(12) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(13) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(14) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(15) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(16) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(17) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(18) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(19) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(20) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(21) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(22) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(23) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(24) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(25) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(26) X"20"
change /mp3_cpu/TM/VHDL_MEMORY/mem(27) X"52"
change /mp3_cpu/TM/VHDL_MEMORY/mem(28) X"0D"
change /mp3_cpu/TM/VHDL_MEMORY/mem(29) X"0E"
change /mp3_cpu/TM/VHDL_MEMORY/mem(30) X"01"
change /mp3_cpu/TM/VHDL_MEMORY/mem(31) X"64"
change /mp3_cpu/TM/VHDL_MEMORY/mem(32) X"C0"
change /mp3_cpu/TM/VHDL_MEMORY/mem(33) X"C1"
change /mp3_cpu/TM/VHDL_MEMORY/mem(34) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(35) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(36) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(37) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(38) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(39) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(40) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(41) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(42) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(43) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(44) X"0C"
change /mp3_cpu/TM/VHDL_MEMORY/mem(45) X"0E"
change /mp3_cpu/TM/VHDL_MEMORY/mem(46) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(47) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(48) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(49) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(50) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(51) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(52) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(53) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(54) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(55) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(56) X"02"
change /mp3_cpu/TM/VHDL_MEMORY/mem(57) X"64"
change /mp3_cpu/TM/VHDL_MEMORY/mem(58) X"05"
change /mp3_cpu/TM/VHDL_MEMORY/mem(59) X"0E"
change /mp3_cpu/TM/VHDL_MEMORY/mem(60) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(61) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(62) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(63) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(64) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(65) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(66) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(67) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(68) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(69) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(70) X"FF"
change /mp3_cpu/TM/VHDL_MEMORY/mem(71) X"0F"
change /mp3_cpu/TM/VHDL_MEMORY/mem(72) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(73) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(74) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(75) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(76) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(77) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(78) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(79) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(80) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(81) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(82) X"1E"
change /mp3_cpu/TM/VHDL_MEMORY/mem(83) X"00"
change /mp3_cpu/TM/VHDL_MEMORY/mem(84) X"0D"
change /mp3_cpu/TM/VHDL_MEMORY/mem(85) X"60"
change /mp3_cpu/TM/VHDL_MEMORY/mem(86) X"DD"
change /mp3_cpu/TM/VHDL_MEMORY/mem(87) X"BA"
run 5
echo "Done loading ../mp3/ECE411/mp3/tests/traptest.asm program code."
