-- VHDL Entity ece411.ADDR_SPLIT1.generatedInstance
--
-- Created:
--          by - styve1.ews (evrt-252-27.ews.illinois.edu)
--          at - 20:12:00 04/03/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY ADDR_SPLIT1 IS
   PORT( 
      ADDRESS : IN     LC3b_word;
      index   : OUT    LC3B_C_INDEX;
      offset  : OUT    LC3B_C_OFFSET;
      tag     : OUT    LC3B_C_TAG
   );

END ADDR_SPLIT1 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF ADDR_SPLIT1 IS 
BEGIN


END generatedInstance;
