-- VHDL Entity ece411.BRadd1.generatedInstance
--
-- Created:
--          by - freed2.ews (linux-a3.ews.illinois.edu)
--          at - 13:21:34 02/02/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY BRadd1 IS
   PORT( 
      ADJ9out  : IN     LC3b_word;
      BRaddout : OUT    LC3b_word;
      clk      : IN     std_logic;
      PC2out   : IN     LC3b_word
   );

END BRadd1 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF BRadd1 IS 
BEGIN


END generatedInstance;
