-- VHDL Entity ece411.ByteZext.generatedInstance
--
-- Created:
--          by - freed2.ews (gelib-057-16.ews.illinois.edu)
--          at - 22:18:20 04/16/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;
LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY ByteZext IS
   PORT( 
      B2        : OUT    LC3B_WORD;
      WriteData : IN     LC3b_word
   );

END ByteZext ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF ByteZext IS 
BEGIN


END generatedInstance;
