-- VHDL Entity ece411.ctr_rip_mem.generatedInstance
--
-- Created:
--          by - draguna1.ews (siebl-0218-11.ews.illinois.edu)
--          at - 19:57:24 03/17/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;
LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY ctr_rip_mem IS
   PORT( 
      Control   : IN     Control_Word;
      Load_dMAR : OUT    std_logic;
      Load_dMDR : OUT    std_logic
   );

END ctr_rip_mem ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF ctr_rip_mem IS 
BEGIN


END generatedInstance;
