-- VHDL Entity ece411.delayforflush.generatedInstance
--
-- Created:
--          by - styve1.ews (gelib-057-03.ews.illinois.edu)
--          at - 10:42:14 05/02/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY delayforflush IS
   PORT( 
      Clk      : IN     std_logic;
      flushclk : OUT    STD_LOGIC
   );

END delayforflush ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF delayforflush IS 
BEGIN


END generatedInstance;
