-- VHDL Entity ece411.DELAY3.generatedInstance
--
-- Created:
--          by - styve1.ews (gelib-057-03.ews.illinois.edu)
--          at - 09:51:16 05/02/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY DELAY3 IS
   PORT( 
      A         : OUT    STD_LOGIC;
      writeback : IN     std_logic
   );

END DELAY3 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF DELAY3 IS 
BEGIN


END generatedInstance;
