-- VHDL Entity ece411.Delay2.generatedInstance
--
-- Created:
--          by - styve1.ews (gelib-057-08.ews.illinois.edu)
--          at - 10:08:07 05/01/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;
LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY Delay2 IS
   PORT( 
      D_ADDR : OUT    LC3b_word;
      F24    : IN     LC3B_WORD
   );

END Delay2 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF Delay2 IS 
BEGIN


END generatedInstance;
