-- VHDL Entity ece411.fiveDelay.generatedInstance
--
-- Created:
--          by - styve1.ews (evrt-252-09.ews.illinois.edu)
--          at - 21:59:59 04/29/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;
LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY fiveDelay IS
   PORT( 
      D_ADDR : OUT    LC3b_word;
      F7     : IN     LC3B_WORD
   );

END fiveDelay ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF fiveDelay IS 
BEGIN


END generatedInstance;
