-- VHDL Entity ece411.HighSig.generatedInstance
--
-- Created:
--          by - draguna1.ews (siebl-0220-12.ews.illinois.edu)
--          at - 15:41:29 04/15/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;
LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY HighSig IS
   PORT( 
      C : OUT    STD_LOGIC
   );

END HighSig ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF HighSig IS 
BEGIN


END generatedInstance;
