-- VHDL Entity ece411.IFETCH.symbol
--
-- Created:
--          by - draguna1.ews (gelib-057-27.ews.illinois.edu)
--          at - 17:16:34 03/20/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;
LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY IFETCH IS
   PORT( 
      BrADDR    : IN     LC3B_WORD;
      Clk       : IN     std_logic;
      I_DATAIN  : IN     LC3b_word;
      I_MRESP_H : IN     std_logic;
      PCMuxSel  : IN     STD_LOGIC;
      RESET_L   : IN     std_logic;
      I_MREAD_L : OUT    STD_LOGIC;
      Instr     : OUT    LC3b_word;
      iADDR     : OUT    LC3b_word;
      iPC       : OUT    LC3b_word
   );

-- Declarations

END IFETCH ;

--
-- VHDL Architecture ece411.IFETCH.struct
--
-- Created:
--          by - draguna1.ews (gelib-057-27.ews.illinois.edu)
--          at - 17:16:34 03/20/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;
LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY mp3lib;

ARCHITECTURE struct OF IFETCH IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL Output   : LC3b_word;
   SIGNAL PCMuxOut : LC3B_WORD;

   -- Implicit buffer signal declarations
   SIGNAL iPC_internal : LC3b_word;


   -- Component Declarations
   COMPONENT PLUS2
   PORT (
      PCin    : IN     LC3b_word ;
      PCplus2 : OUT    LC3b_word 
   );
   END COMPONENT;
   COMPONENT Reg16
   PORT (
      Input  : IN     LC3b_word ;
      RESET  : IN     std_logic ;
      clk    : IN     std_logic ;
      load   : IN     std_logic ;
      Output : OUT    LC3b_word 
   );
   END COMPONENT;
   COMPONENT MUX2_16
   PORT (
      A   : IN     LC3B_WORD ;
      B   : IN     LC3B_WORD ;
      SEL : IN     STD_LOGIC ;
      F   : OUT    LC3B_WORD 
   );
   END COMPONENT;
   COMPONENT NOT1
   PORT (
      A : IN     STD_LOGIC ;
      F : OUT    STD_LOGIC 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : MUX2_16 USE ENTITY mp3lib.MUX2_16;
   FOR ALL : NOT1 USE ENTITY mp3lib.NOT1;
   FOR ALL : PLUS2 USE ENTITY ece411.PLUS2;
   FOR ALL : Reg16 USE ENTITY ece411.Reg16;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   PCPlus2 : PLUS2
      PORT MAP (
         PCin    => Output,
         PCplus2 => iPC_internal
      );
   PC : Reg16
      PORT MAP (
         Input  => PCMuxOut,
         RESET  => RESET_L,
         clk    => Clk,
         load   => Clk,
         Output => Output
      );
   iMAR : Reg16
      PORT MAP (
         Input  => Output,
         RESET  => RESET_L,
         clk    => Clk,
         load   => Clk,
         Output => iADDR
      );
   iMDR : Reg16
      PORT MAP (
         Input  => I_DATAIN,
         RESET  => RESET_L,
         clk    => Clk,
         load   => I_MRESP_H,
         Output => Instr
      );
   PCMux : MUX2_16
      PORT MAP (
         A   => iPC_internal,
         B   => BrADDR,
         SEL => PCMuxSel,
         F   => PCMuxOut
      );
   U_0 : NOT1
      PORT MAP (
         A => Clk,
         F => I_MREAD_L
      );

   -- Implicit buffered output assignments
   iPC <= iPC_internal;

END struct;
