-- VHDL Entity ece411.JMPADDR.generatedInstance
--
-- Created:
--          by - draguna1.ews (siebl-0220-12.ews.illinois.edu)
--          at - 15:41:29 04/15/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;
LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY JMPADDR IS
   PORT( 
      ADJ11      : IN     lc3b_word;
      iPC        : IN     lc3b_word;
      JMPAddress : OUT    lc3b_word
   );

END JMPADDR ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF JMPADDR IS 
BEGIN


END generatedInstance;
