-- VHDL Entity ece411.L2_LRU_Next_Val.symbol
--
-- Created:
--          by - draguna1.ews (gelib-057-08.ews.illinois.edu)
--          at - 01:23:17 04/30/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all; 
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY L2_LRU_Next_Val IS
   PORT( 
      Hit0       : IN     std_logic;
      Hit1       : IN     std_logic;
      Hit2       : IN     std_logic;
      Hit3       : IN     std_logic;
      Hit4       : IN     std_logic;
      Hit5       : IN     std_logic;
      Hit6       : IN     std_logic;
      Hit7       : IN     std_logic;
      LRUDataOut : IN     lc3b_tree;
      LRUDataIn  : OUT    lc3b_tree
   );

-- Declarations

END L2_LRU_Next_Val ;

--
-- VHDL Architecture ece411.L2_LRU_Next_Val.struct
--
-- Created:
--          by - draguna1.ews (gelib-057-08.ews.illinois.edu)
--          at - 01:23:17 04/30/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all; 
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY mp3lib;

ARCHITECTURE struct OF L2_LRU_Next_Val IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL F        : std_logic;
   SIGNAL F1       : std_logic;
   SIGNAL F2       : std_logic;
   SIGNAL F3       : std_logic;
   SIGNAL F4       : std_logic;
   SIGNAL F5       : std_logic;
   SIGNAL Out6     : std_logic;
   SIGNAL dataout0 : std_logic;
   SIGNAL dataout1 : std_logic;
   SIGNAL dataout2 : std_logic;
   SIGNAL dataout3 : std_logic;
   SIGNAL dataout4 : std_logic;
   SIGNAL dataout5 : std_logic;
   SIGNAL dataout6 : std_logic;
   SIGNAL out0     : std_logic;
   SIGNAL out1     : std_logic;
   SIGNAL out2     : std_logic;
   SIGNAL out3     : std_logic;
   SIGNAL out4     : std_logic;
   SIGNAL out5     : std_logic;


   -- Component Declarations
   COMPONENT OR2
   PORT (
      A : IN     std_logic ;
      B : IN     std_logic ;
      F : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT bitmux2
   PORT (
      A      : IN     std_logic ;
      B      : IN     std_logic ;
      Sel    : IN     std_logic ;
      bitout : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT lc3b_treeSplitter
   PORT (
      LRUData  : IN     lc3b_tree ;
      dataout0 : OUT    std_logic ;
      dataout1 : OUT    std_logic ;
      dataout2 : OUT    std_logic ;
      dataout3 : OUT    std_logic ;
      dataout4 : OUT    std_logic ;
      dataout5 : OUT    std_logic ;
      dataout6 : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT lc3b_treeconcat
   PORT (
      In0     : IN     std_logic ;
      In1     : IN     std_logic ;
      In2     : IN     std_logic ;
      In3     : IN     std_logic ;
      In4     : IN     std_logic ;
      In5     : IN     std_logic ;
      In6     : IN     std_logic ;
      dataout : OUT    lc3b_tree 
   );
   END COMPONENT;
   COMPONENT NOR3
   PORT (
      A : IN     STD_LOGIC ;
      B : IN     STD_LOGIC ;
      C : IN     STD_LOGIC ;
      F : OUT    STD_LOGIC 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : NOR3 USE ENTITY mp3lib.NOR3;
   FOR ALL : OR2 USE ENTITY ece411.OR2;
   FOR ALL : bitmux2 USE ENTITY ece411.bitmux2;
   FOR ALL : lc3b_treeSplitter USE ENTITY ece411.lc3b_treeSplitter;
   FOR ALL : lc3b_treeconcat USE ENTITY ece411.lc3b_treeconcat;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : OR2
      PORT MAP (
         A => Hit0,
         B => Hit1,
         F => F
      );
   U_1 : OR2
      PORT MAP (
         A => Hit2,
         B => Hit3,
         F => F1
      );
   U_2 : OR2
      PORT MAP (
         A => Hit4,
         B => Hit5,
         F => F2
      );
   U_3 : OR2
      PORT MAP (
         A => Hit6,
         B => Hit7,
         F => F3
      );
   U_4 : OR2
      PORT MAP (
         A => F,
         B => F1,
         F => F4
      );
   U_9 : OR2
      PORT MAP (
         A => F2,
         B => F3,
         F => F5
      );
   U_5 : bitmux2
      PORT MAP (
         A      => dataout0,
         B      => F,
         Sel    => F,
         bitout => out0
      );
   U_6 : bitmux2
      PORT MAP (
         A      => dataout1,
         B      => F1,
         Sel    => F1,
         bitout => out1
      );
   U_7 : bitmux2
      PORT MAP (
         A      => dataout2,
         B      => F2,
         Sel    => F2,
         bitout => out2
      );
   U_8 : bitmux2
      PORT MAP (
         A      => dataout3,
         B      => F3,
         Sel    => F3,
         bitout => out3
      );
   U_10 : bitmux2
      PORT MAP (
         A      => dataout4,
         B      => F,
         Sel    => F4,
         bitout => out4
      );
   U_11 : bitmux2
      PORT MAP (
         A      => dataout5,
         B      => F2,
         Sel    => F5,
         bitout => out5
      );
   U_12 : lc3b_treeSplitter
      PORT MAP (
         LRUData  => LRUDataOut,
         dataout0 => dataout0,
         dataout1 => dataout1,
         dataout2 => dataout2,
         dataout3 => dataout3,
         dataout4 => dataout4,
         dataout5 => dataout5,
         dataout6 => dataout6
      );
   U_13 : lc3b_treeconcat
      PORT MAP (
         In0     => out0,
         In1     => out1,
         In2     => out2,
         In3     => out3,
         In4     => out4,
         In5     => out5,
         In6     => Out6,
         dataout => LRUDataIn
      );
   U_14 : NOR3
      PORT MAP (
         A => Hit5,
         B => Hit6,
         C => Hit7,
         F => Out6
      );

END struct;
