-- VHDL Entity ece411.L2Mux.symbol
--
-- Created:
--          by - draguna1.ews (gelib-057-08.ews.illinois.edu)
--          at - 01:26:46 04/30/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all; 
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY L2Mux IS
   PORT( 
      In0    : IN     std_logic;
      In1    : IN     std_logic;
      In2    : IN     std_logic;
      In3    : IN     std_logic;
      In4    : IN     std_logic;
      In5    : IN     std_logic;
      In6    : IN     std_logic;
      In7    : IN     std_logic;
      P0     : IN     std_logic;
      P1     : IN     std_logic;
      P2     : IN     std_logic;
      P3     : IN     std_logic;
      P4     : IN     std_logic;
      P5     : IN     std_logic;
      P6     : IN     std_logic;
      P7     : IN     std_logic;
      Output : OUT    std_logic
   );

-- Declarations

END L2Mux ;

--
-- VHDL Architecture ece411.L2Mux.struct
--
-- Created:
--          by - draguna1.ews (gelib-057-08.ews.illinois.edu)
--          at - 01:26:46 04/30/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all; 
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;


ARCHITECTURE struct OF L2Mux IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL F    : std_logic;
   SIGNAL F1   : std_logic;
   SIGNAL F2   : std_logic;
   SIGNAL F3   : std_logic;
   SIGNAL F4   : std_logic;
   SIGNAL F5   : std_logic;
   SIGNAL F6   : std_logic;
   SIGNAL F7   : std_logic;
   SIGNAL Out4 : std_logic;
   SIGNAL Out5 : std_logic;


   -- Component Declarations
   COMPONENT AND2
   PORT (
      A : IN     std_logic ;
      B : IN     std_logic ;
      F : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT OR2
   PORT (
      A : IN     std_logic ;
      B : IN     std_logic ;
      F : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT OR4Bit
   PORT (
      A    : IN     std_logic ;
      B    : IN     std_logic ;
      C    : IN     std_logic ;
      D    : IN     std_logic ;
      Out4 : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : AND2 USE ENTITY ece411.AND2;
   FOR ALL : OR2 USE ENTITY ece411.OR2;
   FOR ALL : OR4Bit USE ENTITY ece411.OR4Bit;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : AND2
      PORT MAP (
         A => In0,
         B => P0,
         F => F
      );
   U_1 : AND2
      PORT MAP (
         A => In1,
         B => P1,
         F => F1
      );
   U_2 : AND2
      PORT MAP (
         A => In2,
         B => P2,
         F => F2
      );
   U_3 : AND2
      PORT MAP (
         A => In3,
         B => P3,
         F => F3
      );
   U_4 : AND2
      PORT MAP (
         A => In4,
         B => P4,
         F => F4
      );
   U_5 : AND2
      PORT MAP (
         A => In5,
         B => P5,
         F => F5
      );
   U_6 : AND2
      PORT MAP (
         A => In6,
         B => P6,
         F => F6
      );
   U_7 : AND2
      PORT MAP (
         A => In7,
         B => P7,
         F => F7
      );
   U_10 : OR2
      PORT MAP (
         A => Out4,
         B => Out5,
         F => Output
      );
   U_8 : OR4Bit
      PORT MAP (
         A    => F,
         B    => F1,
         C    => F2,
         D    => F3,
         Out4 => Out4
      );
   U_9 : OR4Bit
      PORT MAP (
         A    => F4,
         B    => F5,
         C    => F6,
         D    => F7,
         Out4 => Out5
      );

END struct;
