-- VHDL Entity ece411.LDBDataRip.generatedInstance
--
-- Created:
--          by - freed2.ews (gelib-057-16.ews.illinois.edu)
--          at - 22:18:20 04/16/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;
LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY LDBDataRip IS
   PORT( 
      A1       : OUT    LC3B_WORD;
      B1       : OUT    LC3B_WORD;
      D_DATAIN : IN     LC3b_word
   );

END LDBDataRip ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF LDBDataRip IS 
BEGIN


END generatedInstance;
