-- VHDL Entity ece411.MakeEven.generatedInstance
--
-- Created:
--          by - freed2.ews (linux-a3.ews.illinois.edu)
--          at - 14:50:14 02/02/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY MakeEven IS
   PORT( 
      ALUout     : IN     LC3b_word;
      ALUoutEven : OUT    LC3b_word;
      clk        : IN     std_logic
   );

END MakeEven ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF MakeEven IS 
BEGIN


END generatedInstance;
