-- VHDL Entity ece411.MemStoreAddressCalc1.generatedInstance
--
-- Created:
--          by - styve1.ews (evrt-252-27.ews.illinois.edu)
--          at - 20:12:00 04/03/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY MemStoreAddressCalc1 IS
   PORT( 
      index        : IN     LC3B_C_INDEX;
      Tagarray0out : IN     LC3B_C_TAG;
      Tagarray1out : IN     LC3B_C_TAG;
      Way0ADDR     : OUT    lc3b_word;
      Way1ADDR     : OUT    lc3b_word
   );

END MemStoreAddressCalc1 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF MemStoreAddressCalc1 IS 
BEGIN


END generatedInstance;
