-- VHDL Entity ece411.NOPGEN.generatedInstance
--
-- Created:
--          by - styve1.ews (gelib-057-12.ews.illinois.edu)
--          at - 19:37:56 04/17/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY NOPGEN IS
   PORT( 
      NOP : OUT    Control_word
   );

END NOPGEN ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF NOPGEN IS 
BEGIN


END generatedInstance;
