-- VHDL Entity ece411.Shifter.generatedInstance
--
-- Created:
--          by - draguna1.ews (siebl-0220-12.ews.illinois.edu)
--          at - 15:39:25 04/15/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY Shifter IS
   PORT( 
      ADJ4    : IN     LC3B_WORD;
      RegAOut : IN     LC3b_word;
      SFTOUT  : OUT    LC3b_word;
      SHFTOP  : IN     LC3B_SHFTOP
   );

END Shifter ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF Shifter IS 
BEGIN


END generatedInstance;
