-- VHDL Entity ece411.SIGGEN111.generatedInstance
--
-- Created:
--          by - freed2.ews (gelib-057-16.ews.illinois.edu)
--          at - 22:18:22 04/16/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY SIGGEN111 IS
   PORT( 
      B : OUT    LC3b_reg
   );

END SIGGEN111 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF SIGGEN111 IS 
BEGIN


END generatedInstance;
