-- VHDL Entity ece411.STD_ONE2.generatedInstance
--
-- Created:
--          by - styve1.ews (evrt-252-27.ews.illinois.edu)
--          at - 20:12:00 04/03/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY STD_ONE2 IS
   PORT( 
      ONE_OUT : OUT    std_logic
   );

END STD_ONE2 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF STD_ONE2 IS 
BEGIN


END generatedInstance;
