-- VHDL Entity ece411.STD_ONE2.generatedInstance
--
-- Created:
--          by - freed2.ews (gelib-057-15.ews.illinois.edu)
--          at - 23:05:39 04/03/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY STD_ONE2 IS
   PORT( 
      ONE_OUT : OUT    std_logic
   );

END STD_ONE2 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF STD_ONE2 IS 
BEGIN


END generatedInstance;
