-- VHDL Entity ece411.WRITEBACK.symbol
--
-- Created:
--          by - freed2.ews (gelib-057-25.ews.illinois.edu)
--          at - 00:25:13 03/21/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;
LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY WRITEBACK IS
   PORT( 
      ALUout    : IN     LC3B_WORD;
      Control   : IN     Control_Word;
      DEST      : IN     Lc3b_reg;
      ReadData  : IN     LC3B_WORD;
      SRCA      : IN     LC3b_reg;
      SRCB      : IN     LC3b_reg;
      DestOut   : OUT    Lc3b_reg;
      REG_Write : OUT    std_logic;
      RegData   : OUT    LC3B_WORD;
      SRCAOut   : OUT    LC3b_reg;
      SRCBOut   : OUT    LC3b_reg
   );

-- Declarations

END WRITEBACK ;

--
-- VHDL Architecture ece411.WRITEBACK.struct
--
-- Created:
--          by - freed2.ews (gelib-057-25.ews.illinois.edu)
--          at - 00:25:13 03/21/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;
LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY mp3lib;

ARCHITECTURE struct OF WRITEBACK IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL RFMuxSel : std_logic;


   -- Component Declarations
   COMPONENT ctl_rip_wb
   PORT (
      Control   : IN     Control_Word ;
      RFMuxSel  : OUT    std_logic ;
      REG_Write : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT MUX2_16
   PORT (
      A   : IN     LC3B_WORD ;
      B   : IN     LC3B_WORD ;
      SEL : IN     STD_LOGIC ;
      F   : OUT    LC3B_WORD 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : MUX2_16 USE ENTITY mp3lib.MUX2_16;
   FOR ALL : ctl_rip_wb USE ENTITY ece411.ctl_rip_wb;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 DestPass
   DestOut <= DEST;
   SRCAOut <= SRCA;
   SRCBOut <= SRCB;                                 


   -- Instance port mappings.
   U_1 : ctl_rip_wb
      PORT MAP (
         Control   => Control,
         RFMuxSel  => RFMuxSel,
         REG_Write => REG_Write
      );
   U_0 : MUX2_16
      PORT MAP (
         A   => ReadData,
         B   => ALUout,
         SEL => RFMuxSel,
         F   => RegData
      );

END struct;
